// seanxyz/src/app/footer/footer.component.ts
import { Component, OnInit } from '@angular/core';
import { Link } from '../Classes/Link';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.css']
})
export class FooterComponent implements OnInit {

  socials: Link[] = [
    {text: 'Github', route: '', url: 'https://github.com/seanpmyers'},
    {text: 'Linkedin', route: '', url: 'https://www.linkedin.com/in/spmyers/'},
    {text: 'Twitter', route: '', url: 'https://twitter.com/spmyers22'},
    {text: 'Resume', route: '', url: 'https://docs.google.com/document/d/1GvKfnmHnWzW7AckQHn0XvsXMfQyNxsPtllkFYW8SQNc/edit?usp=sharing'}
  ]

  constructor() { }

  ngOnInit() {
  }

}

<ul>
  <li *ngFor="let social of socials" >
    <a href={{social.url}} target="_blank" >
      {{social.text}}
    </a>
  </li>
</ul>

// 2.0_React/websiteapp/src/components/nav/Footer.tsx
import * as React from 'react';
import "roboto-fontface"
import "./Footer.css"

class Footer extends React.Component {
  public render() {
    return (
      <section className="footer">
        <div className="footer-canvas">
          <div className="navbar-grid">
            <a href="https://www.facebook.com/spmyers22" target="_blank" className="footer-item" id="Facebook">
              Facebook
				    </a>
            <a href="https://twitter.com/spmyers22" target="_blank" className="footer-item" id="Twitter">
              Twitter
				    </a>
            <a href="https://www.linkedin.com/in/spmyers/" target="_blank" className="footer-item" id="Linkedin">
              Linkedin
				    </a>
            <a href="https://github.com/seanpmyers" target="_blank" className="footer-item" id="Github">
              Github
				    </a>
          </div>
        </div>
      </section>
    );
  }
}

export default Footer;
